package id.ac.poliban.mi.aulia.customlistview;

import java.util.ArrayList;
import java.util.List;

public class CountryData {

    static List<Country> getAllCountries(){
        List<Country> data =  new ArrayList<>();
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png", "Indonesia","Republik Indonesia (RI) atau Negara Kesatuan Republik Indonesia (NKRI), atau lebih umum disebut Indonesia, adalah negara di Asia Tenggara yang dilintasi garis khatulistiwa dan berada di antara daratan benua Asia dan Australia, serta antara Samudra Pasifik dan Samudra Hindia. Indonesia adalah negara kepulauan terbesar di dunia yang terdiri dari 17.504 pulau.[11] Nama alternatif yang biasa dipakai adalah Nusantara.[12] Dengan populasi Hampir 270.054.853 jiwa pada tahun 2018,[13] Indonesia adalah negara berpenduduk terbesar keempat di dunia dan negara yang berpenduduk Muslim terbesar di dunia, dengan lebih dari 230 juta jiwa.[14][15"));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/125px-Flag_of_Japan.svg.png", "Jepang","Jepang (Jepang: 日本 Nippon atau Nihon; nama resmi: 日本国 Tentang suara ini Nipponkoku atau Nihonkoku, nama harfiah: \"Negara Jepang\") adalah sebuah negara kepulauan di Asia Timur. Letaknya di ujung barat Samudra Pasifik, di sebelah timur Laut Jepang, dan bertetangga dengan Republik Rakyat Tiongkok, Korea, dan Rusia. Pulau-pulau paling utara berada di Laut Okhotsk, dan wilayah paling selatan berupa kelompok pulau-pulau kecil di Laut Tiongkok Timur, tepatnya di sebelah selatan Okinawa yang bertetangga dengan Taiwan."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/125px-Flag_of_Zimbabwe.svg.png", "Zimbabwe","Republik Zimbabwe adalah sebuah negara di Afrika bagian selatan. Negara yang terkurung daratan ini berbatasan dengan Afrika Selatan di sebelah selatan, Botswana di barat, Zambia di utara dan Mozambik di timur. Emmerson Mnangagwa adalah presiden Zimbabwe saat ini."));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/125px-Flag_of_Germany.svg.png", "Jerman","Republik Federal Jerman (bahasa Jerman: Bundesrepublik Deutschland) adalah negara berbentuk federasi di Eropa Barat. Negara ini memiliki posisi ekonomi dan politik yang sangat penting di Eropa maupun di dunia. Dengan luas 357.021 kilometer persegi (kira-kira dua setengah kali pulau Jawa) dan penduduk sekitar 82 juta jiwa, negara dengan 16 negara bagian (Bundesland, jamak: Bundesländer) ini menjadi anggota kunci organisasi Uni Eropa (penduduk terbanyak), penghubung transportasi barang dan jasa antarnegara sekawasan, serta menjadi negara dengan penduduk imigran ketiga terbesar di dunia.[9]"));
        data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/125px-Flag_of_the_People%27s_Republic_of_China.svg.png", "RRC","Republik Rakyat Tiongkok (Hanzi sederhana: 中华人民共和国; Hanzi tradisional: 中華人民共和國; Pinyin: Zhōnghuá Rénmín Gònghéguó; Pe̍h-ōe-jī: Tiong-hôa Jîn-bîn Kiōng-hô-kok; harfiah: 'Republik Rakyat Tionghoa', disingkat RRT, China atau Tiongkok) adalah sebuah negara yang terletak di Asia Timur yang beribu kota di Beijing[20] Negara ini memiliki jumlah penduduk terbanyak di dunia (sekitar 1,4 milyar jiwa) dan luas wilayah 9,69 juta kilometer persegi, menjadikannya negara ke-3 terbesar di dunia.[21] Negara ini didirikan pada tahun 1949 setelah berakhirnya Perang Saudara Tiongkok, dan sejak saat itu dipimpin oleh sebuah partai tunggal, yaitu Partai Komunis Tiongkok (PKT).[22] Sekalipun seringkali dilihat sebagai negara komunis, kebanyakan ekonomi republik ini telah diswastakan sejak tahun 1980-an. Walau bagaimanapun, pemerintah masih mengawasi ekonominya secara politik terutama dengan perusahaan-perusahaan milik pemerintah dan sektor perbankan. Secara politik, ia masih tetap menjadi pemerintahan satu partai.\n" +
                "\n" +
                "Sebagai negara dengan penduduk terbanyak di dunia, dengan populasi melebihi 1,363 miliar jiwa (diperkirakan pada tahun 2014), yang mayoritas merupakan bangsa Tionghoa. Untuk menekan jumlah penduduk, pemerintah giat menggalakkan kebijakan satu anak. Tiongkok Daratan merupakan istilah yang digunakan untuk merujuk kepada kawasan di bawah pemerintahan RRT dan tidak termasuk kawasan administrasi khusus Hong Kong dan Makau, sementara nama Republik Tiongkok mengacu pada entitas lain yang dulu pernah menguasai Tiongkok sejak tahun 1912 hingga kekalahannya pada Perang Saudara Tiongkok. Saat ini Republik Tiongkok hanya menguasai pulau Taiwan, dan beribu kota di Taipei, oleh karena itu lazim disebut Tionghoa Taipei, terutama dalam even-even olahraga. RRT mengklaim wilayah milik Republik Tiongkok (yang umum dikenal dengan Taiwan) namun tidak memerintahnya, sedangkan Republik Tiongkok mengklaim kedaulatan terhadap seluruh Tiongkok daratan yang saat ini dikuasai RRT. (lihat pula: Status politik Taiwan)[23]"));
        return data;
    }
}
